#!/usr/bin/env sh

alias ls='ls --color'
alias sudo='doas'
alias vim='nvim'
alias vi='vim'
alias python='python3'
alias pip='pip3'
alias l='ls --color -als'
alias gst='git status'
alias tms='tmux-sessionizer'
alias code='/mnt/c/Users/r/AppData/Local/Programs/Microsoft\ VS\ Code/bin/code'
